DELETE http://localhost:8000/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTcxNTU4ODg5MCwidXNlcklkIjoyfQ.GFhtNM8AW6oCtt5szfld-vdsKQoc_JsmFX_BZslhLp4