PUT http://localhost:8000/events/1
content-type: application/json

{
    "name": "updated test",
    "description": "description update",
    "location": "updated location",
    "dateTime": "2025-01-01T15:30:00Z",
    "user_id": 1
}